language: ruby
rvm:
- 2.7.2
install: bundle install
services:
  - postgresql
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rails webpacker:compile
  - bundle exec rails spec