language: ruby
rvm:
- 2.6.6
install: bundle install
services:
  - postgresql
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - bundle exec rspec