default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: task_system

test:
  <<: *default
  database: task_system

production:
  <<: *default
  database: task_system
